spring.application.name=ChemistryLabVR
server.port=10104

spring.datasource.url=jdbc:postgresql://localhost:5432/ChemistryLabVR
spring.datasource.username=postgres
spring.datasource.password=Tdk101004@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect